# Generated by Django 4.2.1 on 2023-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
