# Generated by Django 4.2.1 on 2023-05-21 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0003_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
